# Generated by Django 2.2 on 2019-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190616_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickName',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='昵称'),
        ),
    ]
