# Generated by Django 2.2.2 on 2019-08-27 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190616_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.TextField()),
                ('oauth_type', models.PositiveIntegerField(choices=[(0, 'QQ'), (1, '微信'), (2, '微博')], default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '第三方登陆关联',
            },
        ),
    ]
