# Generated by Django 2.2.2 on 2019-08-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_oauthrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthrelationship',
            options={'verbose_name': '第三方登陆关联', 'verbose_name_plural': ''},
        ),
    ]
