# Generated by Django 2.2.3 on 2019-08-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190827_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauthrelationship',
            options={'verbose_name': '第三方登陆关联', 'verbose_name_plural': '第三方登陆关联'},
        ),
        migrations.AddField(
            model_name='oauthrelationship',
            name='portrait_img_url',
            field=models.URLField(null=True),
        ),
    ]
