# Generated by Django 2.2.3 on 2019-08-28 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190828_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthrelationship',
            name='appid',
            field=models.CharField(max_length=200, verbose_name='用户唯一ID'),
        ),
        migrations.AlterField(
            model_name='oauthrelationship',
            name='oauth_type',
            field=models.PositiveIntegerField(choices=[(0, 'QQ'), (1, '微信'), (2, '微博')], default=0, verbose_name='第三方关联'),
        ),
        migrations.AlterField(
            model_name='oauthrelationship',
            name='portrait_img_url',
            field=models.URLField(null=True, verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='oauthrelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
