# Generated by Django 2.2.2 on 2019-07-30 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20190705_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdatenum',
            name='date',
            field=models.DateField(default=datetime.date(2019, 7, 30)),
        ),
    ]
