# Generated by Django 2.2.2 on 2019-08-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0008_auto_20190827_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdatenum',
            options={'verbose_name': '日期阅读统计', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '博客访问数量', 'verbose_name_plural': ''},
        ),
    ]
