# Generated by Django 2.2.3 on 2019-08-28 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0009_auto_20190827_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readdatenum',
            options={'verbose_name': '日期阅读统计', 'verbose_name_plural': '日期阅读统计'},
        ),
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '博客访问数量', 'verbose_name_plural': '博客访问数量'},
        ),
        migrations.AlterField(
            model_name='readdatenum',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 28)),
        ),
    ]
