# Generated by Django 2.2 on 2019-05-25 14:11

from django.db import migrations, models
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='标题', max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('delete', models.BooleanField(default=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
            bases=(models.Model, read_statistics.models.ReadNumCountExpansion),
        ),
        migrations.CreateModel(
            name='Blog_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='分类')),
                ('delete', models.BooleanField(default=True)),
            ],
        ),
    ]
