# Generated by Django 2.2.2 on 2019-08-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app1', '0003_auto_20190730_1956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-creation_time'], 'verbose_name': '博客', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='blog_type',
            options={'verbose_name': '博客类型', 'verbose_name_plural': ''},
        ),
    ]
