# Generated by Django 2.2.2 on 2019-08-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20190525_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '博客点赞总数', 'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '已点赞的用户', 'verbose_name_plural': ''},
        ),
    ]
