# Generated by Django 2.2.3 on 2019-08-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20190827_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '博客点赞总数'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '已点赞的用户'},
        ),
    ]
