# Generated by Django 2.2.3 on 2019-08-28 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_auto_20190828_0935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likecount',
            options={'verbose_name': '博客点赞总数', 'verbose_name_plural': '博客点赞总数'},
        ),
        migrations.AlterModelOptions(
            name='likerecord',
            options={'verbose_name': '已点赞的用户', 'verbose_name_plural': '已点赞的用户'},
        ),
    ]
